### ISSUE TITLE
pause and menu keybind not working

### ISSUE THREAD

**Issue by Kayocas** [fireundubh/KingmakerMods.pw#1]
Not sure if this is a mod bug or one of the game's bug but the spacebar and the menu and pause keybindings aren't working

**Comment by fireundubh** [comment]
Working fine here.

* What's your game version?
* What's your mod version?
* Are you using Unity Mod Manager or Kingmaker Mod Loader in addition to KingmakerMods.pw?

**Comment by Kayocas** [comment]
At first it was working here as well, the latest game version and mod version, only using your mod. After loading a quicksave the bug appeared.

**Comment by fireundubh** [comment]
When you updated to the new version of the mod, did you update the INI?

**Comment by Kayocas** [comment]
yes I updated the INI, started the game without the mods and the issue was gone. Reinstalling now to see if it fixes the issue

**Comment by Kayocas** [comment]
Reinstalling doesn't fix it.

**Comment by fireundubh** [comment]
Well, first, I need the debug log.

Second, did you enable the highlight objects toggle mod? This is the only mod that has anything to do with keybinds, specifically the HighlightObjectsOff binding (the Tab key).

Also, reinstalling does nothing for Patchwork mods. It's not like Harmony where you need to reinstall after every game update.

**Comment by Kayocas** [comment]
I reinstalled to make sure the INI had been changed and it was already, and no I'm not using the highlight objects mod. How do I get the debug log?

**Comment by aD2R** [comment]
Hi! I just installed v1.0.16 from NexusMods and encountered this issue right away. Game version is GOG v1.1.1e, no other mods or tools. The following keys stop working: Quick Load & Quick Save (tried rebinding to other keys), Pause & Tactical Time Flow (spacebar still works in the dialogues, but not elsewhere), Esc (no response anywhere). Starting a new game results in an error. Without the patcher everything is fine. Guess I'll have to stick to CheatEngine for now. Great mod though. Thanks!
![newgame](https://user-images.githubusercontent.com/45424452/49155173-516c5e80-f32b-11e8-8d5a-46aa610ad2d0.jpg)
[patchwork.log](https://github.com/fireundubh/KingmakerMods.pw/files/2624743/patchwork.log)
[output_log.txt](https://github.com/fireundubh/KingmakerMods.pw/files/2624744/output_log.txt)
[GameLogPrev.txt](https://github.com/fireundubh/KingmakerMods.pw/files/2624745/GameLogPrev.txt)
[GameLogFull.txt](https://github.com/fireundubh/KingmakerMods.pw/files/2624746/GameLogFull.txt)

**Comment by fireundubh** [comment]
@Kayocas @aD2R:

Looking at @aD2R's log, I would bet that when both of you installed 1.0.16, you didn't update the INI when the installer prompted. Because you didn't update the INI, probably because you didn't want to lose your current settings, the mod can't find the **new** settings that were added to the INI, and the INI parser is throwing an exception.

```
[82,3122]: NullReferenceException: Object reference not set to an instance of an object
KingmakerMods.UserConfig.Utilities.TrimAll () (at <ce7a2e7c39614ae6a8d3ccb1a6c99337>:0)
>>>>>> KingmakerMods.UserConfig.Parser.GetValueAsBool () (at <ce7a2e7c39614ae6a8d3ccb1a6c99337>:0)
Kingmaker.UI.KeyboardAccess.IsModReady () (at <ce7a2e7c39614ae6a8d3ccb1a6c99337>:0)
Kingmaker.UI.KeyboardAccess.RegisterBuiltinBindings () (at <ce7a2e7c39614ae6a8d3ccb1a6c99337>:0)
Kingmaker.Game.Initialize () (at <ce7a2e7c39614ae6a8d3ccb1a6c99337>:0)
Kingmaker.Runner.Start () (at <ce7a2e7c39614ae6a8d3ccb1a6c99337>:0)
```

The `KeyboardAccess.RegisterBuiltinBindings` method is a bad place for an exception to be thrown for obvious reasons.

In the next version, the INI parser will defer to default values when settings are missing. In the meantime, fix your INI files.

Add this to `[Cheats]`:
```
; When true, you and your party will never fail skill checks.
bNeverFailSkillChecks = false
```

Add this section:

```
[UI.HighlightObjectsToggle]

; When true, pressing the Tab key will toggle object highlighting on/off until the key is pressed again.
; Highlighting will automatically toggle off during combat and area transitions.
bEnabled = false

; If you experience lag while highlighting is enabled, increase this value. This rate controls how fast
; overtips (e.g., nameplates) are updated for newly highlighted units.
iSecondsBetweenTicksGameTime = 1
```

**Comment by aD2R** [comment]
@fireundubh 
>when you installed 1.0.16, you didn't update the INI when the installer prompted

Thing is this was the first ever installation of your mod, there was no KingmakerMods.ini in gamedir, so there were no prompts. I've even reinstalled it now (after deleting the INI), same result. My file has all the values you suggested including, by default. I didn't make a single change, yet the issue persists.
[KingmakerMods.ini (untouched)](https://github.com/fireundubh/KingmakerMods.pw/files/2628758/KingmakerMods.txt)
[GameLogFull.txt](https://github.com/fireundubh/KingmakerMods.pw/files/2628759/GameLogFull.txt)

**Comment by PonyFlare** [comment]
I am here with the identical issue. I downloaded and installed the mod for the first time 2 days ago. I got that error message aD2R posted on first run. Quit and reloaded and didn't have that issue, but the inability to pause/unpause is a significant issue that makes the game unplayable. Menu can at least still be accessed with the button at bottom left of UI even if Esc doesn't work. I even tried changing the keybinding to something other than the spacebar and it still failed.

**Comment by fireundubh** [comment]
Try v1.0.17 now on the Nexus.

**Comment by PonyFlare** [comment]
Everything's working properly now! Thanks!

**Comment by aD2R** [comment]
Yup, v1.0.17 works just right. Tested with both default and modified INI. Thank you so much @fireundubh!

**Comment by fireundubh** [comment]
I'd like to hear from @Kayocas, too, but two confirmations is good enough to close. Thanks for reporting and testing.
