### ISSUE TITLE
Launcher kicking out DLC part of game

### ISSUE THREAD

**Issue by 33Funny007** [fireundubh/KingmakerMods.pw#2]
[GameLogFull.txt](https://github.com/fireundubh/KingmakerMods.pw/files/2705205/GameLogFull.txt)

**Comment by fireundubh** [comment]
To enable DLC, achievements, time played statistics, etc., the game must be launched via Steam or Galaxy. In v1.0.19, a feature was added that allows you to launch the game through a client. Click the "set client path" button and select the folder containing Steam.exe or GalaxyClient.exe.

![](https://i.imgur.com/prYd7FD.png)
